version: "3.9"

services:
  app:
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=$POSTGRES_DB
      - DB_USER=$POSTGRES_USER
      - DB_PASS=$POSTGRES_PASSWORD
      - DB_PORT=5432
    depends_on:
      - "db"
  db:
    env_file:
      - .env
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgres/data
    environment:
    - POSTGRES_DB=$POSTGRES_DB
    - POSTGRES_USER=$POSTGRES_USER
    - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    ports:
      - "5432:5432"
  
  redis:
    image: redis:7.0-alpine
    restart: unless-stopped
    ports:
      - 6379:6379

  celery-worker:
    build: .
    command: >
      sh -c "celery -A immigrationback worker -l DEBUG"
    depends_on:
      - db
      - redis
    restart: unless-stopped

volumes:
  dev-db-data:

      
    
    
    